---
language: node_js
node_js:
  - "6"

branches:
  except:
  - /^dependabot\/.*$/

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn lint
  - yarn run build
  - yarn run test:coverage --runInBand
  - yarn run test:ember

before_deploy:
  - yarn global add auto-dist-tag@1
  - auto-dist-tag --write

deploy:
  provider: npm
  skip_cleanup: true
  email: info@simplabs.com
  api_key:
    secure: bgluRZGT8aoFWAMKd5dDDg/YeYrHHx/ABtI1oCVJF4QIMfuITadt2NZ8vfUKeeD3zJo9nhz7yS4ni7y+ut+VihZkY9F2aMClnJj12QgeXUILox322s092x+gI9WQqpd5JJ1CD9K0AI+3NgdIMO6nw2pyHoEncydrgbkEX7WoQL3Qx6ji1XIpCHJDtq+jJJVAQo1HEXvGxV3k4aAsvsWGlws/d637IYp9KgxDKmLCiBLHuvfAvHQJ/e/MXIhOp0Xwl8+AHKR77FM4Sx818s9o0VKc1YeKecfn/lzHGdBHBDNpqd8gebGrRbBoQ+0CfGi4pTpzwwVGaQepV8U3NLq2aTXGcDCEmTEBGZpIcKxMEXKxXngIJQTy4EBCaDu5uVsUNt1JMvEdqoo7EKy4X1gVDOmWh88rmkCKJ0U6E6ZtoGGLH+D/TjtH96Gmbbg5IntKDLWvgREExxmaec3Xes7GswMOWKRqnVRXWE9mhbUtJozwyD4cYCWTVFcuSPCyNGY0ZVPmNPo32afMoyUJRp2KeXALJxC0H5+MvPCHuIpidY8mouGcFnK9hmFw0BLWHfuJFxMhspKMJx/5SgKaQdRNZeRoDMKuYNusLnMKC2L9TEt1GrNAhhhznvv+4RSVPEiIxAKEdx1Q38kiP3NypNJpc3ykMXeosLcLu/R7ento0xc=
  on:
    tags: true
    repo: simplabs/qunit-dom
